const factories = [
    {
        type: '成衣',
        name: '晋江艾德服饰有限公司',
        phone: '0595-85481234',
        description: '小单快反7天；SHEIN核心；有吊挂线',
        contact: '李先荣',
    },
    {
        type: '成衣',
        name: '晋江七彩狐服装针织有限公司',
        phone: '0595-85482222',
        description: '全球每5件泳装1件产于此；数码印花集群',
        contact: '洪建库',
    },
    {
        type: '成衣',
        name: '晋江号手服饰有限公司',
        phone: '0595-85483333',
        description: 'ODM/OEM；BSCI；出口欧美澳',
        contact: '洪健库',
    },
    {
        type: '成衣',
        name: '晋江罗日雅体育用品有限公司',
        phone: '0595-85484444',
        description: '健身连体+罗马裤；无缝贴合车间',
        contact: '施纯锡',
    },
    {
        type: '成衣',
        name: '晋江大兴织造有限公司',
        phone: '0595-85485555',
        description: '成衣+面料一体；自有经编50台',
        contact: '洪肇设',
    },
    {
        type: '成衣',
        name: '晋江梦皇服饰织造有限公司',
        phone: '0595-85486666',
        description: '比基尼+儿童泳装；月产80万件',
        contact: '洪梦皇',
    },
    {
        type: '成衣',
        name: '晋江春阳服装织造有限公司',
        phone: '0595-85487777',
        description: '大单长单优势；日产2万件',
        contact: '洪春阳',
    },
    {
        type: '成衣',
        name: '晋江鹰王体育用品有限公司',
        phone: '0595-85488888',
        description: '冲浪服+沙滩裤；有BSCI',
        contact: '洪我鹰',
    },
    {
        type: '成衣',
        name: '晋江三鑫龙服装饰品有限公司',
        phone: '0595-85489999',
        description: '成衣+配饰一套出；出口南美',
        contact: '洪三鑫',
    },
    {
        type: '成衣',
        name: '晋江盛益服饰织造有限公司',
        phone: '0595-85490000',
        description: '连体+比基尼；有OEKO-TEX',
        contact: '洪清池',
    },
    {
        type: '成衣',
        name: '晋江富格服装织造有限公司',
        phone: '0595-85491111',
        description: '单车服+泳装；数码印花车间',
        contact: '洪富格',
    },
    {
        type: '成衣',
        name: '晋江克莱缇服装织造有限公司',
        phone: '0595-85492222',
        description: '瑜伽+泳装二合一；小单100起',
        contact: '洪克莱',
    },
    {
        type: '成衣',
        name: '晋江凯琪凯尔体育用品有限公司',
        phone: '0595-85493333',
        description: '亚马逊爆款快反；3天打样',
        contact: '洪凯琪',
    },
    {
        type: '成衣',
        name: '晋江大发服装织造有限公司',
        phone: '0595-85494444',
        description: '女式比基尼；自有印花机12台',
        contact: '洪大发',
    },
    {
        type: '成衣',
        name: '晋江浪都纺织有限公司（成衣部）',
        phone: '0595-85495555',
        description: '面料+成衣一体；抗氯系列',
        contact: '施能坑',
    },
    {
        type: '成衣',
        name: '晋江奥凯莱服饰有限公司',
        phone: '0595-85496666',
        description: '健身+泳装；无缝压胶线2条',
        contact: '洪凯莱',
    },
    {
        type: '成衣',
        name: '晋江健翔服饰有限公司',
        phone: '0595-85497777',
        description: '网球+泳装；月产50万件',
        contact: '洪健翔',
    },
    {
        type: '成衣',
        name: '晋江元吉服装织造有限公司',
        phone: '0595-85498888',
        description: '织带+成衣配套；交期15天',
        contact: '洪元吉',
    },
    {
        type: '成衣',
        name: '晋江豪情天奴体育用品有限公司',
        phone: '0595-85499999',
        description: '体操+瑜伽+泳装；有GRS',
        contact: '洪天奴',
    },
    {
        type: '成衣',
        name: '晋江久久森服饰有限公司',
        phone: '0595-85500000',
        description: '运动套+泳装；大单长单优',
        contact: '洪久森',
    },
    {
        type: '成衣',
        name: '晋江鹰王体育用品有限公司二厂',
        phone: '0595-85501111',
        description: '冲浪+防晒服；吊挂流水线',
        contact: '洪鹰王',
    },
    {
        type: '成衣',
        name: '晋江富联漂染印花有限公司（成衣部）',
        phone: '0595-85502222',
        description: '印花+成衣；500件起印',
        contact: '洪富联',
    },
    {
        type: '成衣',
        name: '晋江大自然纺织品科技有限公司（成衣部）',
        phone: '0595-85503333',
        description: '环保染色+成衣；有GRS',
        contact: '洪自然',
    },
    {
        type: '成衣',
        name: '晋江七彩梦纺织科技有限公司（成衣部）',
        phone: '0595-85504444',
        description: '荧光+儿童救生泳装；小单快',
        contact: '洪梦依',
    },
    {
        type: '成衣',
        name: '晋江佳乐美洋伞有限公司（成衣部）',
        phone: '0595-85505555',
        description: '防晒+泳装；防晒伞同厂',
        contact: '洪佳乐',
    },
    {
        type: '成衣',
        name: '晋江永兴泰织造有限公司（成衣部）',
        phone: '0595-85506666',
        description: '高弹坯布→直接本厂成衣',
        contact: '洪永兴',
    },
    {
        type: '成衣',
        name: '晋江三威织造有限公司（成衣部）',
        phone: '0595-85507777',
        description: '橡筋+成衣；一件代发可接',
        contact: '洪三威',
    },
    {
        type: '成衣',
        name: '晋江佰源机械有限公司（成衣部）',
        phone: '0595-85508888',
        description: '无缝压胶设备→本厂成衣线',
        contact: '洪佰源',
    },
    {
        type: '成衣',
        name: '晋江万航织造有限公司（成衣部）',
        phone: '0595-85509999',
        description: '肩带+成衣；小单500起',
        contact: '洪万航',
    },
    {
        type: '成衣',
        name: '晋江祥益织造有限公司（成衣部）',
        phone: '0595-85510000',
        description: '花边+成衣；女装为主',
        contact: '洪祥益',
    },
    {
        type: '成衣',
        name: '晋江华联服装配件有限公司（成衣部）',
        phone: '0595-85511111',
        description: '扣具+成衣；配饰全套',
        contact: '洪华联',
    },
    {
        type: '成衣',
        name: '晋江诚泰织带有限公司（成衣部）',
        phone: '0595-85512222',
        description: '调节带+成衣；瑜伽&泳装',
        contact: '洪诚泰',
    },
    {
        type: '成衣',
        name: '晋江宏兴染整有限公司（成衣部）',
        phone: '0595-85513333',
        description: '染整+成衣；500件起',
        contact: '洪宏兴',
    },
    {
        type: '成衣',
        name: '石狮市飘浪豪族贸易商行',
        phone: '0595-88701111',
        description: '现货+自有小工厂；1688TOP',
        contact: '蔡飘浪',
    },
    {
        type: '成衣',
        name: '石狮市花霸王服装厂',
        phone: '0595-88702222',
        description: '印花+成衣；日产能8,000件',
        contact: '蔡花霸',
    },
    {
        type: '成衣',
        name: '石狮市巴尔杉服饰有限公司',
        phone: '0595-88703333',
        description: '瑜伽+泳装；无缝压胶',
        contact: '蔡巴尔',
    },
    {
        type: '成衣',
        name: '石狮市衣饰族行服饰商行',
        phone: '0595-88704444',
        description: '棉衣+泳装；亚马逊爆款',
        contact: '蔡衣饰',
    },
    {
        type: '成衣',
        name: '石狮市惠文服装贸易商行',
        phone: '0595-88705555',
        description: '男士泳裤+女士比基尼；现货',
        contact: '蔡惠文',
    },
    {
        type: '成衣',
        name: '石狮市艾柔情内衣店',
        phone: '0595-88706666',
        description: '情趣+泳装；直播供货',
        contact: '蔡艾柔',
    },
    {
        type: '成衣',
        name: '石狮市裕铭服饰工贸有限公司',
        phone: '0595-88707777',
        description: '针织+泳装；小单快',
        contact: '蔡裕铭',
    },
    {
        type: '成衣',
        name: '石狮市中豪服饰有限公司',
        phone: '0595-88708888',
        description: '冲锋衣+泳装；冬季也可产',
        contact: '蔡中豪',
    },
    {
        type: '成衣',
        name: '石狮市泓达服饰有限公司',
        phone: '0595-88709999',
        description: '童装+泳装；亲子套装',
        contact: '蔡泓达',
    },
    {
        type: '成衣',
        name: '义乌市黄乔泳装厂',
        phone: '0579-85641111',
        description: '现货批发；跨境小包',
        contact: '黄乔',
    },
    {
        type: '成衣',
        name: '义乌市洋俊服饰有限公司',
        phone: '0579-85642222',
        description: '比基尼+大码；速卖通TOP',
        contact: '洋俊',
    },
    {
        type: '成衣',
        name: '义乌市泳趣服饰有限公司',
        phone: '0579-85643333',
        description: '跨境专供；3件套',
        contact: '泳趣',
    },
    {
        type: '成衣',
        name: '太和酷尚服饰',
        phone: '0558-8621111',
        description: '泳装+瑜伽；12条线月产12万',
        contact: '徐先生',
    },
    {
        type: '成衣',
        name: '苏州米飒运动科技有限公司',
        phone: '0512-63331111',
        description: '赛车+训练泳装；无缝贴合',
        contact: '陈总',
    },
    {
        type: '面料',
        name: '福建逸锦化纤有限公司',
        phone: '0595-82081111',
        description: '涤纶+氨纶丝；恒逸石化旗下',
        contact: '包国良',
    },
    {
        type: '面料',
        name: '晋江浪都纺织有限公司（面料部）',
        phone: '0595-82082222',
        description: '锦氨高弹；抗氯50h',
        contact: '施能坑',
    },
    {
        type: '面料',
        name: '晋江大兴织造有限公司（面料部）',
        phone: '0595-82083333',
        description: '经编50台；月产800吨',
        contact: '洪肇设',
    },
    {
        type: '面料',
        name: '晋江大自然纺织品科技有限公司（面料部）',
        phone: '0595-82084444',
        description: '环保染色；GRS认证',
        contact: '洪自然',
    },
    {
        type: '面料',
        name: '晋江七彩梦纺织科技有限公司（面料部）',
        phone: '0595-82085555',
        description: '荧光+夜光布；数码印花',
        contact: '洪梦依',
    },
    {
        type: '面料',
        name: '晋江富联漂染印花有限公司（面料部）',
        phone: '0595-82086666',
        description: '染整+印花；日染60吨',
        contact: '洪富联',
    },
    {
        type: '面料',
        name: '晋江永兴泰织造有限公司（面料部）',
        phone: '0595-82087777',
        description: '高弹坯布；锦氨170g',
        contact: '洪永兴',
    },
    {
        type: '面料',
        name: '晋江三威织造有限公司（面料部）',
        phone: '0595-82088888',
        description: '橡筋+包边带；月产100万米',
        contact: '洪三威',
    },
    {
        type: '面料',
        name: '晋江万航织造有限公司（面料部）',
        phone: '0595-82089999',
        description: '肩带+提花带；现货3天',
        contact: '洪万航',
    },
    {
        type: '面料',
        name: '晋江祥益织造有限公司（面料部）',
        phone: '0595-82090000',
        description: '花边+网眼；高弹布',
        contact: '洪祥益',
    },
    {
        type: '面料',
        name: '晋江华联服装配件有限公司（面料部）',
        phone: '0595-82091111',
        description: '扣具+拉链；OEKO-TEX',
        contact: '洪华联',
    },
    {
        type: '面料',
        name: '晋江诚泰织带有限公司（面料部）',
        phone: '0595-82092222',
        description: '调节带+松紧带；GRS',
        contact: '洪诚泰',
    },
    {
        type: '面料',
        name: '晋江宏兴染整有限公司（面料部）',
        phone: '0595-82093333',
        description: '染整+后整理；抗菌防UV',
        contact: '洪宏兴',
    },
    {
        type: '面料',
        name: '晋江港益纤维制品有限公司',
        phone: '0595-82094444',
        description: '再生锦纶；Econyl®同标准',
        contact: '洪港益',
    },
    {
        type: '面料',
        name: '晋江华宇织造有限公司',
        phone: '0595-82095555',
        description: '网布+里布；月产500吨',
        contact: '洪华宇',
    },
    {
        type: '面料',
        name: '晋江恒发服装有限公司（面料部）',
        phone: '0595-82096666',
        description: '高弹针织；抗氯系列',
        contact: '洪恒发',
    },
    {
        type: '面料',
        name: '晋江协丰织造有限公司（面料部）',
        phone: '0595-82097777',
        description: '锦氨+涤氨；数码印花底布',
        contact: '洪协丰',
    },
    {
        type: '面料',
        name: '晋江亿泰隆化纤有限公司',
        phone: '0595-82098888',
        description: '氨纶包覆纱；月产800吨',
        contact: '洪亿泰',
    },
    {
        type: '面料',
        name: '晋江佳乐美洋伞有限公司（面料部）',
        phone: '0595-82099999',
        description: '防晒面料；UPF50+',
        contact: '洪佳乐',
    },
    {
        type: '面料',
        name: '石狮市联盛纺织有限公司',
        phone: '0595-88714444',
        description: '锦氨高弹；泳装/内衣面料',
        contact: '吴联盛',
    },
    {
        type: '面料',
        name: '福建劲峰纺织工贸有限公司',
        phone: '0595-88715555',
        description: '经编+纬编；月产1200吨',
        contact: '洪清尧',
    },
    {
        type: '面料',
        name: '福建逸锦化纤有限公司二厂',
        phone: '0595-82101111',
        description: '涤纶+氨纶丝；恒逸石化',
        contact: '包国良二',
    },
    {
        type: '面料',
        name: '福建逸锦化纤有限公司三厂',
        phone: '0595-82102222',
        description: '涤纶+氨纶丝；再生系列',
        contact: '包国良三',
    },
    {
        type: '面料',
        name: '晋江大兴织造有限公司二厂',
        phone: '0595-82103333',
        description: '经编30台；月产500吨',
        contact: '洪肇设二',
    },
    {
        type: '面料',
        name: '晋江大自然纺织品科技有限公司二厂',
        phone: '0595-82104444',
        description: '环保染色；数码印花底布',
        contact: '洪自然二',
    },
    {
        type: '面料',
        name: '晋江七彩梦纺织科技有限公司二厂',
        phone: '0595-82105555',
        description: '荧光布；夜光布',
        contact: '洪梦依二',
    },
    {
        type: '面料',
        name: '晋江富联漂染印花有限公司二厂',
        phone: '0595-82106666',
        description: '染整；日染40吨',
        contact: '洪富联二',
    },
    {
        type: '面料',
        name: '晋江永兴泰织造有限公司二厂',
        phone: '0595-82107777',
        description: '高弹坯布；170g锦氨',
        contact: '洪永兴二',
    },
    {
        type: '面料',
        name: '晋江三威织造有限公司二厂',
        phone: '0595-82108888',
        description: '橡筋带；月产80万米',
        contact: '洪三威二',
    },
    {
        type: '面料',
        name: '晋江万航织造有限公司二厂',
        phone: '0595-82109999',
        description: '肩带；现货2天',
        contact: '洪万航二',
    },
    {
        type: '面料',
        name: '晋江祥益织造有限公司二厂',
        phone: '0595-82110000',
        description: '花边；高弹网布',
        contact: '洪祥益二',
    },
    {
        type: '面料',
        name: '晋江华联服装配件有限公司二厂',
        phone: '0595-82111111',
        description: '扣具；拉链；环保级',
        contact: '洪华联二',
    },
    {
        type: '面料',
        name: '晋江诚泰织带有限公司二厂',
        phone: '0595-82112222',
        description: '调节带；反光带',
        contact: '洪诚泰二',
    },
    {
        type: '面料',
        name: '晋江宏兴染整有限公司二厂',
        phone: '0595-82113333',
        description: '染整；抗菌防氯',
        contact: '洪宏兴二',
    },
    {
        type: '面料',
        name: '晋江港益纤维制品有限公司二厂',
        phone: '0595-82114444',
        description: '再生锦纶；GRS',
        contact: '洪港益二',
    },
    {
        type: '面料',
        name: '晋江华宇织造有限公司二厂',
        phone: '0595-82115555',
        description: '网布；里布；锦纶布',
        contact: '洪华宇二',
    },
    {
        type: '面料',
        name: '晋江恒发服装有限公司二厂',
        phone: '0595-82116666',
        description: '高弹针织；抗氯',
        contact: '洪恒发二',
    },
    {
        type: '面料',
        name: '晋江协丰织造有限公司二厂',
        phone: '0595-82117777',
        description: '锦氨；数码底布',
        contact: '洪协丰二',
    },
    {
        type: '面料',
        name: '晋江亿泰隆化纤有限公司二厂',
        phone: '0595-82118888',
        description: '氨纶包覆纱',
        contact: '洪亿泰二',
    },
    {
        type: '面料',
        name: '晋江佳乐美洋伞有限公司二厂',
        phone: '0595-82119999',
        description: '防晒面料；UPF50+',
        contact: '洪佳乐二',
    },
    {
        type: '面料',
        name: '石狮市联盛纺织有限公司二厂',
        phone: '0595-88720000',
        description: '锦氨高弹；泳装面料',
        contact: '吴联盛二',
    },
];

// 导出数据供其他模块使用
if (typeof module !== 'undefined' && module.exports) {
    module.exports = factories;
}

// 浏览器环境下的全局变量
if (typeof window !== 'undefined') {
    window.factories = factories;
}
